import Head from "next/head";

import { api } from "~/utils/api";
import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

export default function Home() {
  const { data } = api.post.getAll.useQuery();

  const user = useUser();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          {user.isSignedIn && (
            <button className=" rounded-full bg-red-400 px-3 text-slate-700">
              <SignOutButton />
            </button>
          )}

          {!user.isSignedIn && (
            <button className=" rounded-full bg-green-400 px-3 text-slate-700">
              <SignInButton />
            </button>
          )}
        </div>
        <div>{data?.map((post) => <div>{post.content}</div>)}</div>
      </main>
    </>
  );
}
