import Head from "next/head";
import Image from "next/image";

import { RouterOutputs, api } from "~/utils/api";

import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";

import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

const CreatePostWizard = () => {
  const { user } = useUser();

  console.log(user);

  if (!user) return null;

  return (
    <div className="flex gap-4">
      <Image
        className=" rounded-full"
        src={user.imageUrl}
        width={50}
        height={50}
        alt="user image"
      />
      <input
        className=" grow bg-transparent outline-none"
        placeholder="Type some emojis!"
        type="text"
      />
    </div>
  );
};

type PostWithAuthor = RouterOutputs["post"]["getAll"][number];

const PostView = (props: PostWithAuthor) => {
  const { post, author } = props;
  return (
    <ul>
      <div className="flex gap-3 border-b border-slate-200 p-4" key={post.id}>
        <Image
          className=" rounded-full"
          height={44}
          width={44}
          src={author.imageUrl}
          alt="author image"
        />
        <div className="flex flex-col">
          <p>
            {`@${author.username}  · `}
            <span className=" font-extralight">
              {`${dayjs(post.createdAt).fromNow()}`}
            </span>
          </p>
          {post.content}
        </div>
      </div>
    </ul>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();
  if (isLoading) return <div>Loading...</div>;
  if (!data) return <div>Something went wrong</div>;

  return (
    <>
      <Head>
        <title>Emojigram</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" container mx-auto flex justify-center">
        {user.isSignedIn && (
          <div className="flex h-screen w-full flex-col border-x border-slate-200">
            <div className="border p-4">
              <CreatePostWizard />
            </div>
            {data.map((post) => (
              <PostView {...post} />
            ))}

            {/* <div className="flex content-center">
              <button className="h-10 rounded-full bg-red-400 px-3 text-slate-700">
                <SignOutButton />
              </button>
            </div> */}
          </div>
        )}

        {!user.isSignedIn && (
          <button className=" rounded-full bg-green-400 px-3 text-slate-700">
            <SignInButton />
          </button>
        )}
      </main>
    </>
  );
}
